[phases.setup]
nixPkgs = ['python311', 'gcc']

[phases.install]
cmds = ['python -m pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['pip install gunicorn']

[start]
cmd = 'gunicorn app:app' 