[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python run.py"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
numReplicas = 2

[deploy.env]
PYTHON_VERSION = "3.11.8"
FLASK_APP = "app.py"
FLASK_ENV = "production"
  